### ISSUE TITLE
The versionfile parameter is not working. 

### ISSUE THREAD

**Issue by Patrick-Magee** [awslabs/aws-codedeploy-plugin#105]
No matter what I entered for this parameter, it still generates a temporary file name for the S3 bucket.
![CodeDeploy-plug-in](https://user-images.githubusercontent.com/47974300/58319049-fcf4f800-7e10-11e9-8e92-db3167274966.PNG)

private RevisionLocation zipAndUpload(AWSClients aws, String projectName, FilePath sourceDirectory) throws IOException, InterruptedException, IllegalArgumentException {

        File zipFile = null;
        File versionFile;
        versionFile = new File(sourceDirectory + "/" + versionFileName);

        InputStreamReader reader = null;
        String version = null;
        try {
          reader = new InputStreamReader(new FileInputStream(versionFile), "UTF-8");
          char[] chars = new char[(int) versionFile.length() -1];
          reader.read(chars);
          version = new String(chars);
          reader.close();
        } catch (IOException e) {
          e.printStackTrace();
        } finally {
          if(reader !=null){reader.close();}
        }

        if (version != null){
          zipFile = new File("/tmp/" + projectName + "-" + version + ".zip");
          final boolean fileCreated = zipFile.createNewFile();
          if (!fileCreated) {
            logger.println("File already exists, overwriting: " + zipFile.getPath());
          }
        } else {
          zipFile = File.createTempFile(projectName + "-", ".zip");
        }

**Comment by Patrick-Magee** [comment]
This is a critical issue for us, as we would to generate a dashboard showing what has been deployed onto each environment, and without this parameter AWS Codedeploy just displays a generated text. It doesn't look like this plug-in is being maintained at the moment, as I have been very few recent updates. I would be willing to fix this issue myself, but I have no experience writing Java plug-ins (it's been many years since I worked as a Java programmer)

**Comment by Patrick-Magee** [comment]
This line looks like it's assuming that it is running on a Windows box:

new File("/tmp/" + projectName + "-" + version + ".zip");

**Comment by Patrick-Magee** [comment]
getting this in the Jenkins log: 

java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:242)

It seems to be throwing an end of file exception while trying to read the version text

**Comment by Patrick-Magee** [comment]
char[] chars = new char[(int) versionFile.length() -1];
      reader.read(chars);

**Comment by tylerwalts-dd** [comment]
@Patrick-Magee It works for me.  Try adding `.txt` files to your `Include Files` list?
