### ISSUE TITLE
Access key and secret credentials are not saved

### ISSUE THREAD

**Issue by matthewdfuller** [awslabs/aws-codedeploy-plugin#11]
After installing the plugin, adding it as a build step, and entering credentials (key and secret), I click save. Then, I click "Configure" on the project again and the credentials have disappeared. When building the project, there is then an error:

```
Failed CodeDeploy post-build step; exception follows.
Unable to load AWS credentials from any provider in the chain
com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
	at com.amazonaws.services.codedeploy.AmazonCodeDeployClient.invoke(AmazonCodeDeployClient.java:1919)
	at com.amazonaws.services.codedeploy.AmazonCodeDeployClient.listApplications(AmazonCodeDeployClient.java:620)
	at com.amazonaws.services.codedeploy.AmazonCodeDeployClient.listApplications(AmazonCodeDeployClient.java:1776)
	at com.amazonaws.codedeploy.AWSCodeDeployPublisher.verifyCodeDeployApplication(AWSCodeDeployPublisher.java:218)
	at com.amazonaws.codedeploy.AWSCodeDeployPublisher.perform(AWSCodeDeployPublisher.java:194)
	at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1779)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Build step 'Deploy an application to AWS CodeDeploy' marked build as failure
```

I've tried repeatedly entering the credentials and clicking save, but every time they disappear.

**Comment by matthewdfuller** [comment]
This seems fixed; I hadn't updated to a new version.
