### ISSUE TITLE
NullPointerException in getSourceDirectory

### ISSUE THREAD

**Issue by adamgoucher** [awslabs/aws-codedeploy-plugin#30]
The 'subdirectory' field of my configuration is empty in all my jobs using this plugin, but they have all just started to fail with this exception.

jenkins: 1.622
plugin: 1.6

null
java.lang.NullPointerException
	at com.amazonaws.codedeploy.AWSCodeDeployPublisher.getSourceDirectory(AWSCodeDeployPublisher.java:235)
	at com.amazonaws.codedeploy.AWSCodeDeployPublisher.perform(AWSCodeDeployPublisher.java:215)
	at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Build step 'Deploy an application to AWS CodeDeploy' marked build as failure
Finished: FAILURE

**Comment by suryanarayanan** [comment]
This is fixed in https://github.com/awslabs/aws-codedeploy-plugin/commit/f8ab6c792cd8729d1beec039ddae064b593d3dc4
