### ISSUE TITLE
Deploy Test Fails

### ISSUE THREAD

**Issue by rubberbird** [awslabs/aws-codedeploy-plugin#49]
Jenkins Version: Jenkins ver. 1.588
Code Deploy Plugin Version. 1.8 and 1.9 tested

Process to replicate:

1 - Install plugin manually via the .hpi file.
2- Restarted Jenkins
3 - Create job and add post build action for Code Deploy
4 - Entered required fields
5 - Run Jobs.
6 - Immediate error.

Troubleshooting.

No dependencies are listed, however I checked the plugins/libs folder to confirm the right joda-time version jar was in there. Other than that, not much else to test.

Error Logs:

ERROR: Publisher com.amazonaws.codedeploy.AWSCodeDeployPublisher aborted due to exception
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.auth.AWS4Signer
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at java.lang.Class.newInstance0(Class.java:374)
    at java.lang.Class.newInstance(Class.java:327)
    at com.amazonaws.auth.SignerFactory.createSigner(SignerFactory.java:121)
    at com.amazonaws.auth.SignerFactory.lookupAndCreateSigner(SignerFactory.java:107)
    at com.amazonaws.auth.SignerFactory.getSigner(SignerFactory.java:80)
    at com.amazonaws.AmazonWebServiceClient.computeSignerByServiceRegion(AmazonWebServiceClient.java:311)
    at com.amazonaws.AmazonWebServiceClient.computeSignerByURI(AmazonWebServiceClient.java:284)
    at com.amazonaws.AmazonWebServiceClient.setEndpoint(AmazonWebServiceClient.java:160)
    at com.amazonaws.services.codedeploy.AmazonCodeDeployClient.setEndpoint(AmazonCodeDeployClient.java:1881)
    at com.amazonaws.services.codedeploy.AmazonCodeDeployClient.init(AmazonCodeDeployClient.java:347)
    at com.amazonaws.services.codedeploy.AmazonCodeDeployClient.<init>(AmazonCodeDeployClient.java:231)
    at com.amazonaws.codedeploy.AWSClients.<init>(AWSClients.java:73)
    at com.amazonaws.codedeploy.AWSClients.fromBasicCredentials(AWSClients.java:86)
    at com.amazonaws.codedeploy.AWSCodeDeployPublisher.perform(AWSCodeDeployPublisher.java:196)
    at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
    at hudson.model.Run.execute(Run.java:1784)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Finished: FAILURE

**Comment by aws-turpiej** [comment]
Looks like you are missing the AWS SDK. That's listed as a dependency (which itself would bring in joda time)

https://github.com/awslabs/aws-codedeploy-plugin/blob/master/pom.xml#L53

**Comment by rubberbird** [comment]
Thanks for the suggestion. The strange thing is that if I do a fresh jenkins and install just this plugin, it works fine. I guess it is either an issue with Maven getting the depencies or conflicting joda-time.jars, as there are about 20 on this server from other plugins. Anything I can do to test the AWS SDK is installed?

**Comment by aws-turpiej** [comment]
You can look for the JAR in your maven libraries. you can use the dependencies:get plugin to fetch a dependency to make sure maven is pulling it correctly.

It seems like you are having a conflict with your other plugins. I don't think there's much we can do from our end.
