### ISSUE TITLE
Can't parameterize the Subdirectory

### ISSUE THREAD

**Issue by sprij** [awslabs/aws-codedeploy-plugin#51]
Trying to parameterize a .net deployment for different environments and not being able to parametrize subdirectory (1.9 version).  

```
java.lang.IllegalArgumentException: Provided path (resolved as '${PROFILE}') is not a subdirectory of the workspace (resolved as '...')
    at com.amazonaws.codedeploy.AWSCodeDeployPublisher.getSourceDirectory(AWSCodeDeployPublisher.java:244)
    at com.amazonaws.codedeploy.AWSCodeDeployPublisher.perform(AWSCodeDeployPublisher.java:218)
    at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
```

**Comment by feverLu** [comment]
Do you mind paste what is the parameterize here?  And we can know more details?

**Comment by sprij** [comment]
Sure, the original configuration looked something like this:
![image](https://cloud.githubusercontent.com/assets/6750073/13666226/598f596a-e6a8-11e5-97cf-81a483fa7157.png)

The PROFILE variable maps to solution configurations (this is a .net project). As a workaround I'm using a conditional plugin to split the CodeDeploy configuration per profile so the other parameterization is ok.

**Comment by Jmcfar** [comment]
Hi,

Thanks for the report! This should be fixed in our next plugin release.

**Comment by pmvilaca** [comment]
I've just reported this on CodeDeploy forum. Was looking at jenkins fork of this repo and jenkins jira.. 

https://forums.aws.amazon.com/thread.jspa?messageID=722419

Do you already know when the next release will happen?

**Comment by pmvilaca** [comment]
This will be really helpful when you want to redeploy a previous promotion. Right now, if we want to rollback a deployment, we need a reverse commit because the plugin doesn't support the subdirectory customization. 
Can you please get a new release with this change asap?

**Comment by Jmcfar** [comment]
Cleaning up old issues - This change should be released to the Jenkins plugin repository.
