### ISSUE TITLE
Temporary Credentials Not Working: can't get account aws id

### ISSUE THREAD

**Issue by maorhayoun** [awslabs/aws-codedeploy-plugin#58]
Environment:
Jenkins ver 2.1
AWS CodeDeploy Plugin ver 1.11

May 03, 2016 3:22:20 PM hudson.ExpressionFactory2$JexlExpression evaluate
WARNING: Caught exception evaluating: descriptor.accountId in /$stapler/bound/d85fcff4-ade2-47d7-bddf-854bf0a8fea3/render. Reason: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
...
Caused by: com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
    at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
    at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.invoke(AmazonIdentityManagementClient.java:7398)
    at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.getUser(AmazonIdentityManagementClient.java:4219)
    at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.getUser(AmazonIdentityManagementClient.java:4231)
    at com.amazonaws.codedeploy.AWSClients.getAccountId(AWSClients.java:104)
    at com.amazonaws.codedeploy.AWSCodeDeployPublisher$DescriptorImpl.getAccountId(AWSCodeDeployPublisher.java:528)

i've tried adding the aws key\secret pair at all possible places - jenkins credentials, plugin configuration (under 'manage'), env-injected to specific job - all failed.
using the same pair at "Use Access/Secret keys" option works as expected.
Am i missing something?

**Comment by gaohan137** [comment]
Hi there,

Did you launch your instance with the right role? If yes, do you mind pasting your role here so that we can take a look at it?

The error you are getting: "Unable to load AWS credentials from any provider in the chain" seems to suggest that there is no role associated with the instance.

**Comment by Jmcfar** [comment]
Cleaning up old issues - Closing this as there hasn't been a response. Please feel free to re-open if you are still having the problem.
